Added STRIMZI_UNALTERABLE_TOPIC_CONFIG to topic operator
strimzi/strimzi-kafka-operator pull request #10182
Opened 2024-05-31 10:27 UTC by kahartma

### Type of change

_Select the type of your PR_

- Bugfix
- Enhancement / new feature
- Refactoring
- Documentation

### Description

_Please describe your pull request_

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

2024-05-31 10:34 UTC, scholzj reviewed
Thanks for the PR.

Looking back, I think the decision taken in the community call was wrong. I think the default should be set in the Topic Operator itself and not in Cluster Operator? The way it is implemented now would not allow users to override this configuration when deploying Topic Operator through Cluster Operator. WDYT @ppatierno @tombentley @fvaleri?

2024-05-31 10:49 UTC, kahartma commented on topic-operator/src/main/java/io/strimzi/operator/topic/BatchingTopicController.java
> +            if (!unalterableConfigs.equalsIgnoreCase("NONE")) {
I consciously excluded the ALL case here, because I didn't see why we would want to block all configs, but could be added of course

2024-05-31 15:06 UTC, fvaleri reviewed
> I think the decision taken in the community call was wrong. I think the default should be set in the Topic Operator itself and not in Cluster Operator

@scholzj I agree.

The TO already has the knowledge about CC enablement, so changes should be limited to the topic-operator module.

---

@kahartma thanks for working on this. Some initial comments.

Unalterable and alterable config variables should be mutually exclusive, so we should skip them if they are both set, and also raise a warning (log and status).

We need some more tests in `BatchingTopicControllerTest` to check the various permutations and invalid configs:

- AlterableConfig
  - Happy path
  - Should update with "ALL" or "" (empty string) 
  - Should NOT update with "NONE", "" (empty string), or invalid config (eg: "sdasdas" and "retention.bytes; retention.ms")

- UnalterableConfig
  - Happy path
  - Should NOT update with "ALL" 
  - Should update with "NONE", "" (empty string), or invalid config (eg: "sdasdas" and "retention.bytes; retention.ms")
 
- AlterableConfig and UnalterableConfig
  - Should NOT update 

Probably, we also want to create a documentation paragraph where we explain how to use these new configurations to delegate topic management in a controlled way, but this can be added later as a separate PR.

2024-05-31 15:54 UTC, kahartma commented
> Unalterable and alterable config variables should be mutually exclusive, so we should skip them if they are both set, and also raise a warning (log and status).
Okay, then I would extend this PR a bit more to distinguish between the user-provided `STRIMZI_UNALTERABLE_TOPIC_CONFIG` and making `*.replication.throttled.replicas` unalterable if cruise control is activated? Otherwise we would run into the case that `STRIMZI_ALTERABLE_TOPIC_CONFIG` would be skipped if cruise control is activated and thereby `STRIMZI_UNALTERABLE_TOPIC_CONFIG` is automatically set

2024-05-31 15:56 UTC, kahartma commented on topic-operator/src/test/java/io/strimzi/operator/topic/TopicControllerIT.java
> +                "all", "none", false);
I will then also update all->ALL for alterableTopicConfig to keep it consistent

2024-05-31 16:16 UTC, fvaleri commented
> > Unalterable and alterable config variables should be mutually exclusive, so we should skip them if they are both set, and also raise a warning (log and status).
> 
> @fvaleri Okay, then I would extend this PR a bit more to distinguish between the user-provided `STRIMZI_UNALTERABLE_TOPIC_CONFIG` and making `*.replication.throttled.replicas` unalterable if cruise control is activated? Otherwise we would run into the case that `STRIMZI_ALTERABLE_TOPIC_CONFIG` would be skipped if cruise control is activated and thereby `STRIMZI_UNALTERABLE_TOPIC_CONFIG` is automatically set (and also skipped)

If they are both set at the same time, we go with defaults and raise warnings. 

I would say that CC throttle configurations are "reserved", and they will be always ignored when CC is enabled. This is something that we can clarify in the Javadoc. Does it makes sense?

2024-06-02 20:50 UTC, scholzj commented
> > > Unalterable and alterable config variables should be mutually exclusive, so we should skip them if they are both set, and also raise a warning (log and status).
> > 
> > 
> > @fvaleri Okay, then I would extend this PR a bit more to distinguish between the user-provided `STRIMZI_UNALTERABLE_TOPIC_CONFIG` and making `*.replication.throttled.replicas` unalterable if cruise control is activated? Otherwise we would run into the case that `STRIMZI_ALTERABLE_TOPIC_CONFIG` would be skipped if cruise control is activated and thereby `STRIMZI_UNALTERABLE_TOPIC_CONFIG` is automatically set (and also skipped)
> 
> If they are both set at the same time, we go with defaults and raise warnings.
> 
> I would say that throttle configurations will be always ignored when CC is enabled, unless the user explicitly set them in `.spec.config`. This is something that we can clarify in the Javadoc. Does it makes sense?

I think raising the warning sounds reasonable. But why not allow it? What if the user is using Cruise Control, but at the same time wants to manage the replication throttling for some reason personally through the Topic Operator? I think it is a reasonable default, and reasonable thing to warn against when configuring or in the docs. But not sure I see really a reason to prevent it.

2024-06-06 04:47 UTC, tombentley commented
@fvaleri I think that's reasonable. Better to avoid adding another config if we can avoid it. And the behaviour you describe would do that, so +1 from me.

2024-06-06 06:44 UTC, fvaleri commented
@kahartma so this would actually reduce and simplify the scope of this PR, including testing.

No need to add another environment variable to fix the issue caused by the TO-CC race condition while a throttled rebalance is running. We can simply add a private constant in BatchingTopicController (e.g. CC_THROTTLE_CONFIG) which contains the two throttle config names.

The handling logic (tests) should be:

- If Cruise Control is enabled WITHOUT user throttle configs, we skip any throttle alter config operation without warning
- If Cruise Control is enabled WITH user throttle configs, we reconcile and raise a warning (warning and not error because there is no race when running rebalances without throttling, which is the default)
- If Cruise Control is NOT enabled, we reconcile without warning

That said, there is a general need for setting policies to restrict which topic configurations can be changed by normal users (config management delegation), but we think that this requires a formal design proposal to discuss API changes and how this would work in practice.

2024-06-10 06:02 UTC, fvaleri requested changes
[Required changes.](https://github.com/strimzi/strimzi-kafka-operator/pull/10182#issuecomment-2151525192)

2024-06-13 16:12 UTC, fvaleri commented
@kahartma are you still working on this?

2024-06-19 18:03 UTC, scholzj commented
@kahartma Are you still planning to get back to this? Or should someone else have a look at it?

2024-06-22 18:21 UTC, scholzj commented
As there was nor response for a long time, we are closing it in favour of #10241

2024-06-22 18:21 UTC, closed without merging