Add note about storage check interval of the static quota plugin
strimzi/strimzi-kafka-operator pull request #10335
Opened 2024-07-12 09:35 UTC by fvaleri

### Type of change

- Enhancement

### Description

Add note about storage check interval of the static quota plugin.

### Checklist

- [x] Update documentation

Closes #10311.

2024-07-12 14:40 UTC, scholzj requested changes

2024-07-12 14:40 UTC, scholzj commented on documentation/modules/managing/proc-setting-broker-limits.adoc
> +This is reasonable, but it is possible to change that in `.spec.kafka.config` setting `client.quota.callback.static.storage.check-interval`.
```suggestion
NOTE: Additional options can be configured in the `spec.kafka.config` section.
The full list of supported options can be found in <LinkToTheQuotasPluginRepo>.
```

2024-07-12 14:57 UTC, scholzj commented on documentation/modules/managing/proc-setting-broker-limits.adoc
> +This is reasonable, but it is possible to change that in `.spec.kafka.config` setting `client.quota.callback.static.storage.check-interval`.
Or at least list the other relevant options as well -> the factor fallback and validity duration.

2024-07-12 21:20 UTC, scholzj commented on documentation/modules/managing/proc-setting-broker-limits.adoc
> +The full list of supported options can be found in the https://github.com/fvaleri/kafka-quotas-plugin?tab=readme-ov-file#properties-and-their-defaults[plugin documentation].
```suggestion
The full list of supported options can be found in the https://github.com/strimzi/kafka-quotas-plugin?tab=readme-ov-file#properties-and-their-defaults[plugin documentation].
```

2024-07-13 05:52 UTC, fvaleri commented on documentation/modules/managing/proc-setting-broker-limits.adoc
> +The full list of supported options can be found in the https://github.com/fvaleri/kafka-quotas-plugin?tab=readme-ov-file#properties-and-their-defaults[plugin documentation].
Good catch, thanks!

2024-07-13 09:06 UTC, scholzj approved these changes
Thanks

2024-07-15 09:00 UTC, ppatierno approved these changes

2024-07-17 06:14 UTC, fvaleri commented
@PaulRMellor is this fine for you?

2024-07-17 07:18 UTC, PaulRMellor approved these changes
Thanks

2024-07-18 07:24 UTC, fvaleri commented on documentation/modules/managing/proc-setting-broker-limits.adoc
> +The full list of supported options can be found in the https://github.com/fvaleri/kafka-quotas-plugin?tab=readme-ov-file#properties-and-their-defaults[plugin documentation].
@PaulRMellor we could put the check-interval example in the note, that was my original proposal, but looks like there is no agreement on that.

2024-07-18 08:59 UTC, merged