Update Cruise Control version to 2.5.138
strimzi/strimzi-kafka-operator pull request #10362
Opened 2024-07-19 11:26 UTC by aswinayyolath

### Type of change

- Task

### Description

updated Cruise Control version to 2.5.138. It has a few updates
including fix for High CVE CVE-2023-43642

### Checklist

- [x] Make sure all tests pass
- [x] Update CHANGELOG.md
- [x] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally

2024-07-19 11:30 UTC, scholzj requested changes
The change looks mostly good. We already do this as part of #10343, but we can do it separately as well. But you will have to fix the DCO signoff - the instructions are under the Details link in the PR status section.

2024-07-19 11:30 UTC, scholzj commented on CHANGELOG.md
> +* Update Cruise Control to 2.5.138
We do not track this in CHANGELOG normally. I think you can remove it.

2024-07-19 11:41 UTC, scholzj approved these changes
Great, thanks for the PR!

2024-07-19 11:45 UTC, im-konge approved these changes
Thanks for the PR :)

2024-07-19 12:59 UTC, scholzj commented
/azp run regression

2024-07-20 18:17 UTC, scholzj commented
Thanks for the PR.

2024-07-20 18:17 UTC, merged