Add documentation for CC CORS
strimzi/strimzi-kafka-operator pull request #4030
Opened 2020-12-01 17:47 UTC by kyguy

Signed-off-by: Kyle Liberti <kliberti@redhat.com>

### Type of change

- Documentation

### Description

Documentation for https://github.com/strimzi/strimzi-kafka-operator/pull/3816

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

2020-12-01 18:40 UTC, scholzj approved these changes

2020-12-01 20:56 UTC, ppatierno approved these changes
LGTM. Just a nit.

2020-12-01 20:56 UTC, ppatierno commented on documentation/modules/cruise-control/ref-cruise-control-configuration.adoc
> +== Cross-origin resource sharing configuration
I would use capital letters for making CORS ... "Cross-Origin Resource Sharing configuration"

2020-12-01 20:56 UTC, ppatierno commented on documentation/modules/cruise-control/ref-cruise-control-configuration.adoc
> +By default, cross-origin resource sharing (CORS) for Cruise Control is disabled and can only be enabled for read-only access.
ditto as above

2020-12-04 14:26 UTC, laidan6000 commented
Remember to update the changelog.

2020-12-04 16:17 UTC, laidan6000 requested changes
Peer reviewed.

2020-12-04 16:17 UTC, laidan6000 commented on documentation/modules/cruise-control/ref-cruise-control-configuration.adoc
> +[[cors-configuration]]
Add `[discrete]` after line 43.

2020-12-04 16:17 UTC, laidan6000 commented on documentation/modules/cruise-control/ref-cruise-control-configuration.adoc
> +
_Add a general definition of CORS in a separate paragraph:_

Cross-Origin Resource Sharing (CORS) allows you to specify allowed methods and originating URLs for accessing REST APIs.

2020-12-04 16:17 UTC, laidan6000 commented on documentation/modules/cruise-control/ref-cruise-control-configuration.adoc
> +By default, Cross-Origin Resource Sharing (CORS) for Cruise Control is disabled and can only be enabled for read-only access.
```suggestion
By default, CORS is disabled for the Cruise Control REST API. 
When enabled, only `GET` requests for read-only access to the Kafka cluster state are allowed. 
```

2020-12-04 16:17 UTC, laidan6000 commented on documentation/modules/cruise-control/ref-cruise-control-configuration.adoc
> +This means that applications running in origins different from Strimzi components cannot send POST requests to the Cruise Control API.
```suggestion
This means that external applications, which are running in different origins than the Strimzi components, cannot make `POST` requests to the Cruise Control API. 
```

2020-12-04 16:17 UTC, laidan6000 commented on documentation/modules/cruise-control/ref-cruise-control-configuration.adoc
> +However, these same applications can still send GET requests to the Cruise Control API when cors is enabled for Cruise Control.
```suggestion
However, those applications can make GET requests to access read-only information about the Kafka cluster, such as the current cluster load or the most recent optimization proposal. 
```

2020-12-04 16:17 UTC, laidan6000 commented on documentation/modules/cruise-control/ref-cruise-control-configuration.adoc
> +This prevents third-party applications from manipulating Kafka cluster state through Cruise Control without Strimzi approval but still allows third-party applications to access read-only cluster info
Do we need to say anything about how Strimzi "approves" a CORS request? It feels like some information is missing here.

If nothing else is needed, then I think we can lose the sentence (line 49).

2020-12-04 16:17 UTC, laidan6000 commented on documentation/modules/cruise-control/ref-cruise-control-configuration.adoc
> +
_Add a sub-heading and a new sentence:_

.Enabling CORS for Cruise Control

You enable CORS in `Kafka.spec.cruiseControl.config`.

2020-12-04 16:17 UTC, laidan6000 commented on documentation/modules/cruise-control/ref-cruise-control-configuration.adoc
> +.An example of enabling Cruise Control CORS
I think line 51 can be deleted.

2020-12-04 16:17 UTC, laidan6000 commented on documentation/modules/cruise-control/ref-cruise-control-configuration.adoc
> +
_Add a link to the Wiki:_

For more information, see [REST APIs](https://github.com/linkedin/cruise-control/wiki/REST-APIs) in the Cruise Control Wiki.

2020-12-04 16:17 UTC, laidan6000 commented on documentation/modules/cruise-control/ref-cruise-control-configuration.adoc
> +    config:
Are there any more configuration options for CORS? For example, how do you configure the allowed origins, like you can for the Kafka Bridge?

2020-12-08 10:17 UTC, laidan6000 requested changes
Thanks for making the changes. I've left a few more comments.

2020-12-08 10:17 UTC, laidan6000 commented on documentation/modules/cruise-control/ref-cruise-control-configuration.adoc
> +his means that external applications, which are running in different origins than the Strimzi components, cannot make `POST` requests to the Cruise Control API.
Typo line 49: his.

2020-12-08 10:17 UTC, laidan6000 commented on documentation/modules/cruise-control/ref-cruise-control-configuration.adoc
> +However, those applications can make GET requests to access read-only information about the Kafka cluster, such as the current cluster load or the most recent optimization proposal.
```suggestion
However, those applications can make `GET` requests to access read-only information about the Kafka cluster, such as the current cluster load or the most recent optimization proposal.
```

2020-12-08 10:17 UTC, laidan6000 commented on documentation/modules/cruise-control/ref-cruise-control-configuration.adoc
> +You enable CORS in `Kafka.spec.cruiseControl.config`.
```suggestion
You enable and configure CORS in `Kafka.spec.cruiseControl.config`. 
For example:
```

2020-12-08 16:54 UTC, laidan6000 approved these changes
Changes look good.

2020-12-08 16:55 UTC, laidan6000 commented
Small typo: "You enable ad configure"

2020-12-08 17:00 UTC, kyguy commented
Sorry @laidan6000, I keep missing these typos!

2020-12-08 18:14 UTC, merged

2020-12-08 18:14 UTC, scholzj commented
Thanks @kyguy