[systemtest] Refactor of resource classes and STs - prerequisite for fabric8 upgrade and paralelism PRs
strimzi/strimzi-kafka-operator pull request #4182
Opened 2021-01-05 19:30 UTC by im-konge

Signed-off-by: Lukas Kral <lukywill16@gmail.com>

### Type of change

- Refactoring

### Description

_Please describe your pull request_

### Checklist

- [ ] Make sure all tests pass

2021-01-06 14:31 UTC, im-konge commented
@strimzi-ci run tests test_only profile=regression

2021-01-06 14:31 UTC, Frawless commented
/azp run regression

2021-01-06 15:31 UTC, Frawless commented
/azp run regression

2021-01-06 15:37 UTC, im-konge commented
@strimzi-ci run tests test_only profile=regression

2021-01-07 12:11 UTC, sknot-rh requested changes

2021-01-07 12:11 UTC, sknot-rh commented on systemtest/src/test/java/io/strimzi/systemtest/mirrormaker/MirrorMaker2ST.java
> +        KafkaTopicResource.topic(kafkaClusterSourceName, topicSourceName, 3).build();
```suggestion
        KafkaTopicResource.create(KafkaTopicResource.topic(kafkaClusterSourceName, topicSourceName, 3).build());
```

2021-01-08 01:10 UTC, im-konge commented on systemtest/src/test/java/io/strimzi/systemtest/security/oauth/OauthPlainST.java
> +                kafkaOauthClientJob.create(kafkaOauthClientJob.consumerStrimziOauthPlain().build());
As we are doing for the producer -> I just added deletion of the job. Good catch!

2021-01-08 01:51 UTC, im-konge commented on systemtest/src/test/java/io/strimzi/systemtest/security/oauth/OauthPlainST.java
> +                kafkaOauthClientJob.create(kafkaOauthClientJob.consumerStrimziOauthPlain().build());
1) I added removal of the job (as we have it with producer)
2) the job here wasn't never "deployed" as I'm looking to the history -> it kept the "successful" stage from previous consumer job (which wasn't deleted), now when I'm trying to send messages, the job errors with TLS handshake exception. Just FYI @Frawless 

I'm gonna fix it ASAP

2021-01-08 18:52 UTC, im-konge commented
@strimzi-ci run tests test_only profile=regression

2021-01-08 18:53 UTC, Frawless commented
/azp run regression

2021-01-11 10:49 UTC, im-konge commented
@strimzi-ci run tests true profile=regression testcase=io.strimzi.systemtest.security.oauth.OauthTlsST#testProducerConsumerBridge,io.strimzi.systemtest.security.OpaIntegrationST#testOpaAuthorization,io.strimzi.systemtest.bridge.HttpBridgeKafkaExternalListenersST#testTlsAuthWithWeirdUsername,io.strimzi.systemtest.operators.topic.TopicST#testCreateTopicViaAdminClient,io.strimzi.systemtest.operators.topic.TopicST#testCreateDeleteCreate,io.strimzi.systemtest.operators.topic.TopicST#testTopicModificationOfReplicationFactor,io.strimzi.systemtest.operators.topic.TopicST#testSendingMessagesToNonExistingTopic,io.strimzi.systemtest.operators.topic.TopicST#testMoreReplicasThanAvailableBrokers,io.strimzi.systemtest.operators.topic.TopicST#testCreateTopicViaKafka,io.strimzi.systemtest.log.LoggingChangeST#testJSONFormatLogging,io.strimzi.systemtest.log.LoggingChangeST#testDynamicallySetEOloggingLevels,io.strimzi.systemtest.cruisecontrol.CruiseControlConfigurationST#testCapacityFile,io.strimzi.systemtest.cruisecontrol.CruiseControlConfigurationST#testDeployAndUnDeployCruiseControl,io.strimzi.systemtest.cruisecontrol.CruiseControlConfigurationST#testConfigurationDiskChangeDoNotTriggersRollingUpdateOfKafkaPods,io.strimzi.systemtest.cruisecontrol.CruiseControlConfigurationST#testConfigurationReflection,io.strimzi.systemtest.cruisecontrol.CruiseControlConfigurationST#testConfigurationFileIsCreated,io.strimzi.systemtest.cruisecontrol.CruiseControlConfigurationST#testConfigurationPerformanceOptions,io.strimzi.systemtest.specific.SpecificST#testRackAwareConnectCorrectDeployment,io.strimzi.systemtest.watcher.AllNamespaceST#testUserInDifferentNamespace,io.strimzi.systemtest.tracing.TracingST#testKafkaBridgeService

2021-01-11 11:25 UTC, sknot-rh approved these changes
LGTM

2021-01-11 11:35 UTC, Frawless commented
/azp run regression

2021-01-11 22:11 UTC, im-konge commented
@strimzi-ci run tests true profile=regression testcase=io.strimzi.systemtest.security.oauth.OauthTlsST#testProducerConsumerBridge,io.strimzi.systemtest.security.OpaIntegrationST#testOpaAuthorization,io.strimzi.systemtest.bridge.HttpBridgeKafkaExternalListenersST#testTlsAuthWithWeirdUsername,io.strimzi.systemtest.operators.topic.TopicST#testCreateTopicViaAdminClient,io.strimzi.systemtest.operators.topic.TopicST#testCreateDeleteCreate,io.strimzi.systemtest.operators.topic.TopicST#testTopicModificationOfReplicationFactor,io.strimzi.systemtest.operators.topic.TopicST#testSendingMessagesToNonExistingTopic,io.strimzi.systemtest.operators.topic.TopicST#testMoreReplicasThanAvailableBrokers,io.strimzi.systemtest.operators.topic.TopicST#testCreateTopicViaKafka,io.strimzi.systemtest.log.LoggingChangeST#testJSONFormatLogging,io.strimzi.systemtest.log.LoggingChangeST#testDynamicallySetEOloggingLevels,io.strimzi.systemtest.cruisecontrol.CruiseControlConfigurationST#testCapacityFile,io.strimzi.systemtest.cruisecontrol.CruiseControlConfigurationST#testDeployAndUnDeployCruiseControl,io.strimzi.systemtest.cruisecontrol.CruiseControlConfigurationST#testConfigurationDiskChangeDoNotTriggersRollingUpdateOfKafkaPods,io.strimzi.systemtest.cruisecontrol.CruiseControlConfigurationST#testConfigurationReflection,io.strimzi.systemtest.cruisecontrol.CruiseControlConfigurationST#testConfigurationFileIsCreated,io.strimzi.systemtest.cruisecontrol.CruiseControlConfigurationST#testConfigurationPerformanceOptions,io.strimzi.systemtest.specific.SpecificST#testRackAwareConnectCorrectDeployment,io.strimzi.systemtest.watcher.AllNamespaceST#testUserInDifferentNamespace,io.strimzi.systemtest.tracing.TracingST#testKafkaBridgeService

2021-01-12 00:23 UTC, im-konge commented
@strimzi-ci run tests true profile=regression testcase=io.strimzi.systemtest.security.oauth.OauthTlsST#testProducerConsumerBridge,io.strimzi.systemtest.security.OpaIntegrationST#testOpaAuthorization,io.strimzi.systemtest.bridge.HttpBridgeKafkaExternalListenersST#testTlsAuthWithWeirdUsername,io.strimzi.systemtest.operators.topic.TopicST#testCreateTopicViaAdminClient,io.strimzi.systemtest.operators.topic.TopicST#testCreateDeleteCreate,io.strimzi.systemtest.operators.topic.TopicST#testTopicModificationOfReplicationFactor,io.strimzi.systemtest.operators.topic.TopicST#testSendingMessagesToNonExistingTopic,io.strimzi.systemtest.operators.topic.TopicST#testMoreReplicasThanAvailableBrokers,io.strimzi.systemtest.operators.topic.TopicST#testCreateTopicViaKafka,io.strimzi.systemtest.log.LoggingChangeST#testJSONFormatLogging,io.strimzi.systemtest.log.LoggingChangeST#testDynamicallySetEOloggingLevels,io.strimzi.systemtest.cruisecontrol.CruiseControlConfigurationST#testCapacityFile,io.strimzi.systemtest.cruisecontrol.CruiseControlConfigurationST#testDeployAndUnDeployCruiseControl,io.strimzi.systemtest.cruisecontrol.CruiseControlConfigurationST#testConfigurationDiskChangeDoNotTriggersRollingUpdateOfKafkaPods,io.strimzi.systemtest.cruisecontrol.CruiseControlConfigurationST#testConfigurationReflection,io.strimzi.systemtest.cruisecontrol.CruiseControlConfigurationST#testConfigurationFileIsCreated,io.strimzi.systemtest.cruisecontrol.CruiseControlConfigurationST#testConfigurationPerformanceOptions,io.strimzi.systemtest.specific.SpecificST#testRackAwareConnectCorrectDeployment,io.strimzi.systemtest.watcher.AllNamespaceST#testUserInDifferentNamespace,io.strimzi.systemtest.tracing.TracingST#testKafkaBridgeService

2021-01-12 08:47 UTC, im-konge commented
@strimzi-ci run tests true profile=regression testcase=io.strimzi.systemtest.security.oauth.OauthTlsST#testProducerConsumerBridge,io.strimzi.systemtest.security.OpaIntegrationST#testOpaAuthorization,io.strimzi.systemtest.bridge.HttpBridgeKafkaExternalListenersST#testTlsAuthWithWeirdUsername,io.strimzi.systemtest.operators.topic.TopicST#testCreateTopicViaAdminClient,io.strimzi.systemtest.operators.topic.TopicST#testCreateDeleteCreate,io.strimzi.systemtest.operators.topic.TopicST#testTopicModificationOfReplicationFactor,io.strimzi.systemtest.operators.topic.TopicST#testSendingMessagesToNonExistingTopic,io.strimzi.systemtest.operators.topic.TopicST#testMoreReplicasThanAvailableBrokers,io.strimzi.systemtest.operators.topic.TopicST#testCreateTopicViaKafka,io.strimzi.systemtest.log.LoggingChangeST#testJSONFormatLogging,io.strimzi.systemtest.log.LoggingChangeST#testDynamicallySetEOloggingLevels,io.strimzi.systemtest.cruisecontrol.CruiseControlConfigurationST#testCapacityFile,io.strimzi.systemtest.cruisecontrol.CruiseControlConfigurationST#testDeployAndUnDeployCruiseControl,io.strimzi.systemtest.cruisecontrol.CruiseControlConfigurationST#testConfigurationDiskChangeDoNotTriggersRollingUpdateOfKafkaPods,io.strimzi.systemtest.cruisecontrol.CruiseControlConfigurationST#testConfigurationReflection,io.strimzi.systemtest.cruisecontrol.CruiseControlConfigurationST#testConfigurationFileIsCreated,io.strimzi.systemtest.cruisecontrol.CruiseControlConfigurationST#testConfigurationPerformanceOptions,io.strimzi.systemtest.specific.SpecificST#testRackAwareConnectCorrectDeployment,io.strimzi.systemtest.watcher.AllNamespaceST#testUserInDifferentNamespace,io.strimzi.systemtest.tracing.TracingST#testKafkaBridgeService

2021-01-12 08:49 UTC, im-konge commented
@strimzi-ci run tests true profile=regression testcase=io.strimzi.systemtest.security.oauth.OauthTlsST#testProducerConsumerBridge,io.strimzi.systemtest.security.OpaIntegrationST#testOpaAuthorization,io.strimzi.systemtest.bridge.HttpBridgeKafkaExternalListenersST#testTlsAuthWithWeirdUsername,io.strimzi.systemtest.operators.topic.TopicST#testCreateTopicViaAdminClient,io.strimzi.systemtest.operators.topic.TopicST#testCreateDeleteCreate,io.strimzi.systemtest.operators.topic.TopicST#testTopicModificationOfReplicationFactor,io.strimzi.systemtest.operators.topic.TopicST#testSendingMessagesToNonExistingTopic,io.strimzi.systemtest.operators.topic.TopicST#testMoreReplicasThanAvailableBrokers,io.strimzi.systemtest.operators.topic.TopicST#testCreateTopicViaKafka,io.strimzi.systemtest.log.LoggingChangeST#testJSONFormatLogging,io.strimzi.systemtest.log.LoggingChangeST#testDynamicallySetEOloggingLevels,io.strimzi.systemtest.cruisecontrol.CruiseControlConfigurationST#testCapacityFile,io.strimzi.systemtest.cruisecontrol.CruiseControlConfigurationST#testDeployAndUnDeployCruiseControl,io.strimzi.systemtest.cruisecontrol.CruiseControlConfigurationST#testConfigurationDiskChangeDoNotTriggersRollingUpdateOfKafkaPods,io.strimzi.systemtest.cruisecontrol.CruiseControlConfigurationST#testConfigurationReflection,io.strimzi.systemtest.cruisecontrol.CruiseControlConfigurationST#testConfigurationFileIsCreated,io.strimzi.systemtest.cruisecontrol.CruiseControlConfigurationST#testConfigurationPerformanceOptions,io.strimzi.systemtest.specific.SpecificST#testRackAwareConnectCorrectDeployment,io.strimzi.systemtest.watcher.AllNamespaceST#testUserInDifferentNamespace,io.strimzi.systemtest.tracing.TracingST#testKafkaBridgeService

2021-01-12 15:08 UTC, im-konge commented
@strimzi-ci run tests true profile=regression testcase=io.strimzi.systemtest.security.oauth.OauthTlsST#testProducerConsumerBridge,io.strimzi.systemtest.security.OpaIntegrationST#testOpaAuthorization,io.strimzi.systemtest.bridge.HttpBridgeKafkaExternalListenersST#testTlsAuthWithWeirdUsername,io.strimzi.systemtest.operators.topic.TopicST#testCreateTopicViaAdminClient,io.strimzi.systemtest.operators.topic.TopicST#testCreateDeleteCreate,io.strimzi.systemtest.operators.topic.TopicST#testTopicModificationOfReplicationFactor,io.strimzi.systemtest.operators.topic.TopicST#testSendingMessagesToNonExistingTopic,io.strimzi.systemtest.operators.topic.TopicST#testMoreReplicasThanAvailableBrokers,io.strimzi.systemtest.operators.topic.TopicST#testCreateTopicViaKafka,io.strimzi.systemtest.log.LoggingChangeST#testJSONFormatLogging,io.strimzi.systemtest.log.LoggingChangeST#testDynamicallySetEOloggingLevels,io.strimzi.systemtest.cruisecontrol.CruiseControlConfigurationST#testCapacityFile,io.strimzi.systemtest.cruisecontrol.CruiseControlConfigurationST#testDeployAndUnDeployCruiseControl,io.strimzi.systemtest.cruisecontrol.CruiseControlConfigurationST#testConfigurationDiskChangeDoNotTriggersRollingUpdateOfKafkaPods,io.strimzi.systemtest.cruisecontrol.CruiseControlConfigurationST#testConfigurationReflection,io.strimzi.systemtest.cruisecontrol.CruiseControlConfigurationST#testConfigurationFileIsCreated,io.strimzi.systemtest.cruisecontrol.CruiseControlConfigurationST#testConfigurationPerformanceOptions,io.strimzi.systemtest.specific.SpecificST#testRackAwareConnectCorrectDeployment,io.strimzi.systemtest.watcher.AllNamespaceST#testUserInDifferentNamespace,io.strimzi.systemtest.tracing.TracingST#testKafkaBridgeService

2021-01-12 15:28 UTC, im-konge commented
@strimzi-ci run tests true profile=regression testcase=io.strimzi.systemtest.security.oauth.OauthTlsST#testProducerConsumerBridge,io.strimzi.systemtest.security.OpaIntegrationST#testOpaAuthorization,io.strimzi.systemtest.bridge.HttpBridgeKafkaExternalListenersST#testTlsAuthWithWeirdUsername,io.strimzi.systemtest.operators.topic.TopicST#testCreateTopicViaAdminClient,io.strimzi.systemtest.operators.topic.TopicST#testCreateDeleteCreate,io.strimzi.systemtest.operators.topic.TopicST#testTopicModificationOfReplicationFactor,io.strimzi.systemtest.operators.topic.TopicST#testSendingMessagesToNonExistingTopic,io.strimzi.systemtest.operators.topic.TopicST#testMoreReplicasThanAvailableBrokers,io.strimzi.systemtest.operators.topic.TopicST#testCreateTopicViaKafka,io.strimzi.systemtest.log.LoggingChangeST#testJSONFormatLogging,io.strimzi.systemtest.log.LoggingChangeST#testDynamicallySetEOloggingLevels,io.strimzi.systemtest.cruisecontrol.CruiseControlConfigurationST#testCapacityFile,io.strimzi.systemtest.cruisecontrol.CruiseControlConfigurationST#testDeployAndUnDeployCruiseControl,io.strimzi.systemtest.cruisecontrol.CruiseControlConfigurationST#testConfigurationDiskChangeDoNotTriggersRollingUpdateOfKafkaPods,io.strimzi.systemtest.cruisecontrol.CruiseControlConfigurationST#testConfigurationReflection,io.strimzi.systemtest.cruisecontrol.CruiseControlConfigurationST#testConfigurationFileIsCreated,io.strimzi.systemtest.cruisecontrol.CruiseControlConfigurationST#testConfigurationPerformanceOptions,io.strimzi.systemtest.specific.SpecificST#testRackAwareConnectCorrectDeployment,io.strimzi.systemtest.watcher.AllNamespaceST#testUserInDifferentNamespace,io.strimzi.systemtest.tracing.TracingST#testKafkaBridgeService

2021-01-12 15:57 UTC, im-konge commented
@strimzi-ci run tests true profile=regression testcase=io.strimzi.systemtest.security.oauth.OauthTlsST#testProducerConsumerBridge,io.strimzi.systemtest.security.OpaIntegrationST#testOpaAuthorization,io.strimzi.systemtest.bridge.HttpBridgeKafkaExternalListenersST#testTlsAuthWithWeirdUsername,io.strimzi.systemtest.operators.topic.TopicST#testCreateTopicViaAdminClient,io.strimzi.systemtest.operators.topic.TopicST#testCreateDeleteCreate,io.strimzi.systemtest.operators.topic.TopicST#testTopicModificationOfReplicationFactor,io.strimzi.systemtest.operators.topic.TopicST#testSendingMessagesToNonExistingTopic,io.strimzi.systemtest.operators.topic.TopicST#testMoreReplicasThanAvailableBrokers,io.strimzi.systemtest.operators.topic.TopicST#testCreateTopicViaKafka,io.strimzi.systemtest.log.LoggingChangeST#testJSONFormatLogging,io.strimzi.systemtest.log.LoggingChangeST#testDynamicallySetEOloggingLevels,io.strimzi.systemtest.cruisecontrol.CruiseControlConfigurationST#testCapacityFile,io.strimzi.systemtest.cruisecontrol.CruiseControlConfigurationST#testDeployAndUnDeployCruiseControl,io.strimzi.systemtest.cruisecontrol.CruiseControlConfigurationST#testConfigurationDiskChangeDoNotTriggersRollingUpdateOfKafkaPods,io.strimzi.systemtest.cruisecontrol.CruiseControlConfigurationST#testConfigurationReflection,io.strimzi.systemtest.cruisecontrol.CruiseControlConfigurationST#testConfigurationFileIsCreated,io.strimzi.systemtest.cruisecontrol.CruiseControlConfigurationST#testConfigurationPerformanceOptions,io.strimzi.systemtest.specific.SpecificST#testRackAwareConnectCorrectDeployment,io.strimzi.systemtest.watcher.AllNamespaceST#testUserInDifferentNamespace,io.strimzi.systemtest.tracing.TracingST#testKafkaBridgeService

2021-01-12 16:02 UTC, scholzj approved these changes

2021-01-12 16:38 UTC, Frawless approved these changes
Just make sure that all tests are working, even upgrade tests.

2021-01-12 18:00 UTC, Frawless commented
/azp run regression

2021-01-12 19:15 UTC, im-konge commented
@strimzi-ci run tests test_only profile=regression testcase=io.strimzi.systemtest.security.oauth.OauthTlsST#testProducerConsumerBridge,io.strimzi.systemtest.security.OpaIntegrationST#testOpaAuthorization,io.strimzi.systemtest.bridge.HttpBridgeKafkaExternalListenersST#testTlsAuthWithWeirdUsername,io.strimzi.systemtest.operators.topic.TopicST#testCreateTopicViaAdminClient,io.strimzi.systemtest.operators.topic.TopicST#testCreateDeleteCreate,io.strimzi.systemtest.operators.topic.TopicST#testTopicModificationOfReplicationFactor,io.strimzi.systemtest.operators.topic.TopicST#testSendingMessagesToNonExistingTopic,io.strimzi.systemtest.operators.topic.TopicST#testMoreReplicasThanAvailableBrokers,io.strimzi.systemtest.operators.topic.TopicST#testCreateTopicViaKafka,io.strimzi.systemtest.log.LoggingChangeST#testJSONFormatLogging,io.strimzi.systemtest.log.LoggingChangeST#testDynamicallySetEOloggingLevels,io.strimzi.systemtest.cruisecontrol.CruiseControlConfigurationST#testCapacityFile,io.strimzi.systemtest.cruisecontrol.CruiseControlConfigurationST#testDeployAndUnDeployCruiseControl,io.strimzi.systemtest.cruisecontrol.CruiseControlConfigurationST#testConfigurationDiskChangeDoNotTriggersRollingUpdateOfKafkaPods,io.strimzi.systemtest.cruisecontrol.CruiseControlConfigurationST#testConfigurationReflection,io.strimzi.systemtest.cruisecontrol.CruiseControlConfigurationST#testConfigurationFileIsCreated,io.strimzi.systemtest.cruisecontrol.CruiseControlConfigurationST#testConfigurationPerformanceOptions,io.strimzi.systemtest.specific.SpecificST#testRackAwareConnectCorrectDeployment,io.strimzi.systemtest.watcher.AllNamespaceST#testUserInDifferentNamespace,io.strimzi.systemtest.tracing.TracingST#testKafkaBridgeService

2021-01-12 22:38 UTC, im-konge commented
@strimzi-ci run tests test_only profile=upgrade testcase=StrimziUpgradeST

2021-01-13 08:31 UTC, Frawless commented
/azp run regression

2021-01-13 08:31 UTC, Frawless commented
/azp run upgrade

2021-01-13 12:51 UTC, merged