Fix typo in mirror-maker-2 metrics
strimzi/strimzi-kafka-operator pull request #6744
Opened 2022-04-28 13:14 UTC by maowerner

I just stumbled across this typo while adding some more metrics I wanted here. 

What do you think about also adding `.-+max` everywhere, `fetch-rate` for the consumer and  `record-retry-rate` for the producer in upstream as well? They are recommended for MirrorMaker 2 Performance tuning in Chapter 10 of "Kafka: The definitive Guide" by Shapira, Palino, Sivaram, Petty in addition to the metrics that are already in here.

### Type of change

_Select the type of your PR_

- Bugfix
- Enhancement / new feature
- Refactoring
- Documentation

### Description

_Please describe your pull request_

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

2022-04-28 13:19 UTC, maowerner commented
Please tell me if I should address some of the point in the checklist. It is only a typo in comments, so I thought there is no extensive testing required :sweat_smile:

2022-04-28 13:23 UTC, scholzj commented
> Please tell me if I should address some of the point in the checklist. It is only a typo in comments, so I thought there is no extensive testing required 😅

Thanks for the PR. If I got it right, the fix is just in some comments? In which case - as you said - there is not much to test. But can you please fix the DCO signoff? The instructions should be under the _Details_ link next to the _DCO_ in the status section of the PR.

> What do you think about also adding .-+max everywhere, fetch-rate for the consumer and record-retry-rate for the producer in upstream as well? They are recommended for MirrorMaker 2 Performance tuning in Chapter 10 of "Kafka: The definitive Guide" by Shapira, Palino, Sivaram, Petty in addition to the metrics that are already in here.

I do not have strong opinion about it. If they are useful, then we can for sure add them. WDYT @mimaison @ppatierno?

2022-04-28 18:08 UTC, mimaison commented
Yes these metrics can be useful when tuning MirrorMaker

2022-05-03 13:35 UTC, scholzj requested changes
One more comment apart from the DCO signoff which needs to be fixed. The hange needs to be done to the file in the `packaging/...` directory. The files directly in `examples/` are already released files which should not change outside of a release.

2022-05-19 14:13 UTC, scholzj commented
@maowerner Any plans to get back to this?

2022-05-25 06:47 UTC, closed without merging