Add more kafka connect metrics pattern in source/sink-task-metrics
strimzi/strimzi-kafka-operator pull request #6785
Opened 2022-05-10 01:56 UTC by cdmikechen

### Type of change

- Documentation

### Description
I found some new metrics added (like `sink-record-read-rate` ...) when using the new version of Kafka connect.
These metrics are detailed in official documents <https://docs.confluent.io/platform/current/connect/monitoring.html#sink-task-metrics>
So I think we should these metrics pattern in source/sink-task-metrics.

### Checklist

![image](https://user-images.githubusercontent.com/12069428/167526947-e7045bbe-20ca-485a-b92a-b2dfba440d10.png)

- [ ] Write tests
- [ ] Make sure all tests pass
- [x] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [x] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [x] Supply screenshots for visual changes, such as Grafana dashboards

2022-05-10 08:49 UTC, scholzj requested changes
Thanks for the PR. The change seems reasonable. But can you please make the change only to the file in `packaging/examples`? The file in `examples` is changed only during releases and should not be changed by a regular PR like this.

You will also need to fix the DCO signoff. The instructions should be under the _Details_ link next tot he DCO status.

2022-05-11 00:53 UTC, cdmikechen commented
@scholzj 
Hi~ I've remove unnecessary files and add signoff.

2022-05-11 07:06 UTC, scholzj approved these changes

2022-05-11 09:07 UTC, ppatierno approved these changes

2022-05-11 09:39 UTC, scholzj commented
Thanks for the PR @cdmikechen

2022-05-11 09:39 UTC, merged