Extended `bootstrap. nodePort` to `LoadBalancer` type
strimzi/strimzi-kafka-operator pull request #6923
Opened 2022-06-10 08:15 UTC by ShubhamRwt

### Type of change

_Select the type of your PR_

- Enhancement / new feature

### Description

This PR resolves the issue mentioned in #6894. Now you can define a `kafka.spec.kafka.listeners.configuration.bootstrap.nodePorteven` with a `Loadbalancer` type listener.
### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

2022-06-10 08:38 UTC, scholzj requested changes
You have fixed it only for the bootstrap service. But it would be good to have it also for the per-broker services. It would be also nice to have a test in KafkaClusterTest to check that the port is passed tot he service.

2022-06-10 08:50 UTC, ShubhamRwt commented
Okay on it now

2022-06-10 23:16 UTC, scholzj approved these changes

2022-06-11 00:22 UTC, scholzj commented
/azp run regression

2022-06-11 10:03 UTC, ppatierno approved these changes

2022-06-11 12:08 UTC, scholzj commented
/azp run regression

2022-06-12 21:05 UTC, merged