docs: adds a description of cc modes to the overview
strimzi/strimzi-kafka-operator pull request #7022
Opened 2022-07-06 18:16 UTC by PaulRMellor

Signed-off-by: prmellor <pmellor@redhat.com>

**Documentation change**
Updates the Cruise Control summary in the [Strimzi Overview guide](https://strimzi.io/docs/operators/in-development/overview.html) to describe the new modes that can be used when scaling up/down. 

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [x] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

2022-07-06 18:20 UTC, scholzj approved these changes

2022-07-06 18:35 UTC, ppatierno approved these changes

2022-07-07 08:57 UTC, tomncooper commented on documentation/modules/overview/con-metrics-overview-tools.adoc
> +Generate an optimization proposal in `add-brokers` mode to include any newly added brokers in the rebalance.
```suggestion
Generate an optimization proposal in `add-brokers` mode to move data from existing brokers to newly added ones.
```

2022-07-07 08:58 UTC, tomncooper commented on documentation/modules/overview/con-metrics-overview-tools.adoc
> +Generate an optimization proposal in `remove-brokers` mode to exclude any brokers from the rebalance that are set to be removed.
```suggestion
Generate an optimization proposal in `remove-brokers` mode to move all data off brokers to be removed, before scaling down.
```

2022-07-07 08:58 UTC, tomncooper requested changes
A few tweaks.

2022-07-08 16:36 UTC, scholzj commented
@tomncooper Does this look good now?

2022-07-08 16:42 UTC, tomncooper approved these changes
LGTM

2022-07-08 17:00 UTC, merged