Fix/dashboards ds prometheus
strimzi/strimzi-kafka-operator pull request #7243
Opened 2022-08-26 13:14 UTC by giany

### Type of change

_Select the type of your PR_

- Bugfix

### Description

When trying to add the Grafana dashboards programatically (via helm chart) this error appears:

```
Failed to upgrade legacy queries Datasource ${DS_PROMETHEUS} was not found
```
Seems it's related to this [issue](https://github.com/grafana/grafana/issues/10786). 
### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

2022-08-26 13:18 UTC, scholzj reviewed
Thanks for the PR. Can you please explain why this is needed? The issue you linked seems to talk about Grafana 5 which is quite old and it certainly works fine with newer versions. I do not have any problem with the data sources and nobody else reported anything. We need to make sure that this does not break it for everyone else.

Also, all changes need to be done to the dashabords in the `packaging/examples/metrics/...` directory. Not in the `examples/metrics` directory which is updated only during releases.

2022-08-26 13:31 UTC, giany commented
First if all: if I manually add the .json files to Grafana everything works fine..but I'm working on automatic the process of adding the dashboards as well.
I'm using **kube-prometheus-stack** to deploy Prometheus/Grafana via Terraform+Terragrunt. Config looks like:

```
....
  values_dashboard_kafka = <<VALUES
grafana:
  dashboards:
    default:
      strimzi-kafka-exporter:
        url: https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/main/examples/metrics/grafana-dashboards/strimzi-kafka-exporter.json
      strimzi-zookeeper:
        url: https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/main/examples/metrics/grafana-dashboards/strimzi-zookeeper.json
      strimzi-kafka:
        url: https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/main/examples/metrics/grafana-dashboards/strimzi-kafka.json
VALUES
````

Then **helm_release looks** like:

```
resource "helm_release" "kube-prometheus-stack" {
  count                 = local.kube-prometheus-stack["enabled"] ? 1 : 0
  repository            = local.kube-prometheus-stack["repository"]
  name                  = local.kube-prometheus-stack["name"]
  chart                 = local.kube-prometheus-stack["chart"]
  version               = local.kube-prometheus-stack["chart_version"]
  timeout               = local.kube-prometheus-stack["timeout"]
  force_update          = local.kube-prometheus-stack["force_update"]
  recreate_pods         = local.kube-prometheus-stack["recreate_pods"]
  wait                  = local.kube-prometheus-stack["wait"]
  atomic                = local.kube-prometheus-stack["atomic"]
  cleanup_on_fail       = local.kube-prometheus-stack["cleanup_on_fail"]
  dependency_update     = local.kube-prometheus-stack["dependency_update"]
  disable_crd_hooks     = local.kube-prometheus-stack["disable_crd_hooks"]
  disable_webhooks      = local.kube-prometheus-stack["disable_webhooks"]
  render_subchart_notes = local.kube-prometheus-stack["render_subchart_notes"]
  replace               = local.kube-prometheus-stack["replace"]
  reset_values          = local.kube-prometheus-stack["reset_values"]
  reuse_values          = local.kube-prometheus-stack["reuse_values"]
  skip_crds             = local.kube-prometheus-stack["skip_crds"]
  verify                = local.kube-prometheus-stack["verify"]
  values = compact([
    local.values_kube-prometheus-stack,
    local.cert-manager["enabled"] ? local.values_dashboard_cert-manager : null,
    local.cluster-autoscaler["enabled"] ? local.values_dashboard_cluster-autoscaler : null,
    local.ingress-nginx["enabled"] ? local.values_dashboard_ingress-nginx : null,
    local.thanos["enabled"] ? local.values_dashboard_thanos : null,
    local.argo-cd["enabled"] ? local.values_dashboard_argo : null,
    local.strimzi["enabled"] ? local.values_dashboard_kafka : null,
    local.values_dashboard_node_exporter,
    local.kube-prometheus-stack["thanos_sidecar_enabled"] ? local.values_thanos_sidecar : null,
    local.kube-prometheus-stack["thanos_sidecar_enabled"] ? local.values_grafana_ds : null,
    local.kube-prometheus-stack["default_global_requests"] ? local.values_kps_global_requests : null,
    local.kube-prometheus-stack["default_global_limits"] ? local.values_kps_global_limits : null,
    local.kube-prometheus-stack["extra_values"]
  ])
  namespace = kubernetes_namespace.kube-prometheus-stack.*.metadata.0.name[count.index]

  depends_on = [    
    helm_release.ingress-nginx,
    kubectl_manifest.prometheus-operator_crds
  ]
}

Ok, so once I deploy this..dashboards are also added automatically..but when I try to load them in the browser I get these errors from this image.
<img width="1418" alt="Screenshot 2022-08-26 at 16 29 50" src="https://user-images.githubusercontent.com/814937/186914812-9a17fbc5-a64f-4b27-8e18-99a70839e9b1.png">

A lot of people complain about this with different other .json. PR contains workaround for this issue.

2022-08-26 13:38 UTC, giany commented
@scholzj - so, I should do these changes only in the packaging directory and leave examples as is?

2022-08-26 13:54 UTC, scholzj commented
> @scholzj - so, I should do these changes only in the _packaging/examples_ directory and leave _examples_ as is?

Yes, correct. The `examples` folder is updated only during a release.

> A lot of people complain about this with different other .json. PR contains workaround for this issue.

Well, I'm not questioning that it fixes the issue for you. I'm questioning what it does to other users. That is why it would be good to understand what exactly you are adding and why is it the right way.

The dashabords for example have this today:
```
  "__inputs": [
    {
      "name": "DS_PROMETHEUS",
      "label": "Prometheus",
      "description": "",
      "type": "datasource",
      "pluginId": "prometheus",
      "pluginName": "Prometheus"
    }
  ]
```

How does it fit with it? It looks very similar.

----

PS: I use the Grafana Operator (https://operatorhub.io/operator/grafana-operator) which does nto seem to have any isssues to load the dashboards automatically.

2022-08-26 14:27 UTC, giany commented
I've pushed the changes to the packaging dir. 

This guy had same issue as me: https://github.com/grafana-operator/grafana-operator/issues/75 
It was solved on the operator ..probably that why it works for you.

2022-08-26 14:52 UTC, scholzj commented
Sorry, but I really think we need to understand what it does and why does it do it. When I load it as JSON, it adds the new input field which has some options which are IMHO unexpected -> with data sources which do not exist such as `default`. So it seems a bit weird.

2022-08-26 14:53 UTC, scholzj commented
@strimzi/maintainers Anyone understands Grafana enough to know what this actually does?

2022-09-05 10:18 UTC, ppatierno commented
Tbh I don't know exactly what it does, I just noticed that the PR is reverting back the latest changes on the kafka exporter dashboard about showing `N/A` instead of `0` when no data are available. This is wrong.

2022-09-05 14:45 UTC, Frawless commented
This change adds a new variable that can be referenced in the dashboard json. It also adds a new filter field to the dashboard in grafana:

<img width="1071" alt="image" src="https://user-images.githubusercontent.com/9933303/188473631-86033b47-d273-4585-a37f-a3ac6b4a96bb.png">

For example, here we added `cluster` to be able to pick between different datasources. I remember, that we had to remove the whole `_input` and `datasource` parts when we started syncing dashboards via Argo (we basically used default datasource).

2022-09-10 13:17 UTC, Frawless commented
So I tried to also add it manually to Grafana and it's really weird because I as a user had to specify datasource and the new field kinda doesn't have any value because it doesn't change anything. 

I was able to import it automatically with GrafanaDashboard, but again, if the user doesn't expect to load Strimzi metrics from multiple datasources and switch between them in the dashboard, it looks weird as well.

@giany have you tried to specify `DS_PROMETHEUS` value through chart configuration? There is an option to specify datasource name in Grafana chart so I would expect it should work even with our current version of dashboards.

2022-09-29 14:18 UTC, SuitableProduce commented
I think this is relevant to the conversation: https://github.com/grafana/grafana/issues/10786

2022-12-12 19:18 UTC, devguyio requested changes
@giany Thanks for the PR!

Grafana can be indeed very confusing when it comes to saving and importing dashboards, some ways are intended for manual import, others for provisioning which is not very clear in the docs or the UI.

However,  I'm not sure adding the datasource as a template variable is the correct solution for this particular problem, it's more of a workaround. To provision dashboards you need the raw dashboard JSON (from the dashboard settings) saved to a file (that way there's no DS_PROMETHEUS) and the id is removed.

Can you please confirm that following this path works for your case? You can find it documented in [the administration docs under provisioning](https://grafana.com/docs/grafana/latest/administration/provisioning/#dashboards) . If it works, I think we we can then update the dashboards in the examples to be the raw JSON instead of the ones exported, which should work for both cases of provisioning and manual importing.

2023-01-10 21:41 UTC, scholzj commented
Closing as there was no feedback to this PR for a month.

2023-01-10 21:41 UTC, closed without merging

2023-02-07 09:05 UTC, nicl09 commented
Well, the issue still exists. We are using the kube-prometheus-stack and adding the .json to our deployment as ConfigMap leads to the same error:
```
Failed to upgrade legacy queries Datasource ${DS_PROMETHEUS} was not found
```

ConfigMap:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: strimzi-kafka
  namespace: xxx
  labels:
    app.kubernetes.io/name: prometheus-operator-grafana
    app.kubernetes.io/component: grafana
    grafana_dashboard: "1"
  annotations:
    k8s-sidecar-target-directory: "/tmp/dashboards/k8"
data:
  strimzi-kafka.json: |
    {
      "__inputs": [
        {
          "name": "DS_PROMETHEUS",
          "label": "Prometheus",
          "description": "",
          "type": "datasource",
          "pluginId": "prometheus",
          "pluginName": "Prometheus"
        }
      ],
      "__requires": [
        {
          "type": "grafana",
          "id": "grafana",
          "name": "Grafana",
          "version": "7.3.7"
        },
        {
          "type": "panel",
          "id": "graph",
          "name": "Graph",
          "version": "5.0.0"
        },
        {
          "type": "datasource",
          "id": "prometheus",
          "name": "Prometheus",
          "version": "5.0.0"
        },
        {
          "type": "panel",
          "id": "singlestat",
          "name": "Singlestat",
          "version": "5.0.0"
        }
      ],
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": "-- Grafana --",
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "type": "dashboard"
          }
        ]
      },
      "editable": true,
      "gnetId": null,
      "graphTooltip": 0,
      "iteration": 1600633283203,
      "links": [],
      "panels": [
        {
          "cacheTimeout": null,
          "colorBackground": false,
          "colorValue": true,
          "colors": [
            "#d44a3a",
            "rgba(237, 129, 40, 0.89)",
            "#299c46"
          ],
          "datasource": "${DS_PROMETHEUS}",
          "description": "Number of brokers online",
          "format": "none",
          "gauge": {
            "maxValue": 100,
            "minValue": 0,
            "show": false,
            "thresholdLabels": false,
            "thresholdMarkers": true
          },
          "gridPos": {
            "h": 4,
            "w": 3,
            "x": 0,
            "y": 0
          },
          "id": 46,
          "interval": null,
          "links": [],
          "mappingType": 1,
          "mappingTypes": [
            {
              "name": "value to text",
              "value": 1
            },
            {
              "name": "range to text",
              "value": 2
            }
          ],
          "maxDataPoints": 100,
          "nullPointMode": "connected",
          "nullText": null,
          "postfix": "",
          "postfixFontSize": "50%",
          "prefix": "",
          "prefixFontSize": "50%",
          "rangeMaps": [
            {
              "from": "null",
              "text": "N/A",
              "to": "null"
            }
          ],
          "repeat": null,
          "repeatDirection": "h",
          "sparkline": {
            "fillColor": "rgba(31, 118, 189, 0.18)",
            "full": false,
            "lineColor": "rgb(31, 120, 193)",
            "show": false
          },
          "tableColumn": "",
          "targets": [
            {
              "expr": "count(kafka_server_replicamanager_leadercount{namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\"})",
              "format": "time_series",
              "hide": false,
              "intervalFactor": 1,
              "legendFormat": "",
              "refId": "A"
            }
          ],
          "thresholds": "0,2",
          "title": "Brokers Online",
          "type": "singlestat",
          "valueFontSize": "200%",
          "valueMaps": [
            {
              "op": "=",
              "text": "N/A",
              "value": "null"
            }
          ],
          "valueName": "current"
        },
        {
          "cacheTimeout": null,
          "colorBackground": false,
          "colorValue": true,
          "colors": [
            "#299c46",
            "#e5ac0e",
            "#bf1b00"
          ],
          "datasource": "${DS_PROMETHEUS}",
          "description": "Number of active controllers in the cluster",
          "format": "none",
          "gauge": {
            "maxValue": 100,
            "minValue": 0,
            "show": false,
            "thresholdLabels": false,
            "thresholdMarkers": true
          },
          "gridPos": {
            "h": 4,
            "w": 3,
            "x": 3,
            "y": 0
          },
          "id": 36,
          "interval": null,
          "links": [],
          "mappingType": 1,
          "mappingTypes": [
            {
              "name": "value to text",
              "value": 1
            },
            {
              "name": "range to text",
              "value": 2
            }
          ],
          "maxDataPoints": 100,
          "nullPointMode": "connected",
          "nullText": null,
          "postfix": "",
          "postfixFontSize": "50%",
          "prefix": "",
          "prefixFontSize": "50%",
          "rangeMaps": [
            {
              "from": "null",
              "text": "N/A",
              "to": "null"
            }
          ],
          "sparkline": {
            "fillColor": "rgba(31, 118, 189, 0.18)",
            "full": false,
            "lineColor": "rgb(31, 120, 193)",
            "show": false
          },
          "tableColumn": "",
          "targets": [
            {
              "expr": "sum(kafka_controller_kafkacontroller_activecontrollercount{namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\"})",
              "format": "time_series",
              "hide": false,
              "intervalFactor": 1,
              "refId": "A"
            }
          ],
          "thresholds": "2",
          "title": "Active Controllers",
          "type": "singlestat",
          "valueFontSize": "200%",
          "valueMaps": [
            {
              "op": "=",
              "text": "N/A",
              "value": "null"
            }
          ],
          "valueName": "current"
        },
        {
          "cacheTimeout": null,
          "colorBackground": false,
          "colorValue": true,
          "colors": [
            "#299c46",
            "rgba(237, 129, 40, 0.89)",
            "#d44a3a"
          ],
          "datasource": "${DS_PROMETHEUS}",
          "description": "Unclean leader election rate",
          "format": "none",
          "gauge": {
            "maxValue": 100,
            "minValue": 0,
            "show": false,
            "thresholdLabels": false,
            "thresholdMarkers": true
          },
          "gridPos": {
            "h": 4,
            "w": 3,
            "x": 6,
            "y": 0
          },
          "id": 38,
          "interval": null,
          "links": [],
          "mappingType": 1,
          "mappingTypes": [
            {
              "name": "value to text",
              "value": 1
            },
            {
              "name": "range to text",
              "value": 2
            }
          ],
          "maxDataPoints": 100,
          "nullPointMode": "connected",
          "nullText": null,
          "postfix": "",
          "postfixFontSize": "50%",
          "prefix": "",
          "prefixFontSize": "50%",
          "rangeMaps": [
            {
              "from": "null",
              "text": "N/A",
              "to": "null"
            }
          ],
          "sparkline": {
            "fillColor": "rgba(31, 118, 189, 0.18)",
            "full": false,
            "lineColor": "rgb(31, 120, 193)",
     [...]

2023-02-07 12:28 UTC, SuitableProduce commented
I was able to automatically install Strimzi Grafana dashboards via configmaps with `kubectl create -f dashbords-dir/<all-dashboards.yaml`, by setting datasources to either `Prometheus`, or `null` , depending on where it was required. The configmap has the necessary grafana label so that they get picked up.

I've done the same thing with other projects, and edited the values.yaml with something like `dashboards.enabled`, then at the top of all my new dashboard.yaml's in  `templates/dashboards/` of that chart, I just have the classic `{{ -if  .Values.dashboards.enabled }}`, and then the json below.  Again, these dashboard yamls (with the json inside of them using `|`, have datasource set to `Prometheus`, or `null`

2023-02-07 12:53 UTC, devguyio commented
> Grafana can be indeed very confusing when it comes to saving and importing dashboards, some ways are intended for manual import, others for provisioning which is not very clear in the docs or the UI.
> 
> However, I'm not sure adding the datasource as a template variable is the correct solution for this particular problem, it's more of a workaround. To provision dashboards you need the raw dashboard JSON (from the dashboard settings) saved to a file (that way there's no DS_PROMETHEUS) and the id is removed.
> 
> Can you please confirm that following this path works for your case? You can find it documented in [the administration docs under provisioning](https://grafana.com/docs/grafana/latest/administration/provisioning/#dashboards) . If it works, I think we we can then update the dashboards in the examples to be the raw JSON instead of the ones exported, which should work for both cases of provisioning and manual importing.

Hi Niclas,
Referring to my comment above, can you please try using the "raw dashboard JSON" in the ConfigMap, instead of the the json here in the repo? Meaning:

1. Using a grafana dashboard, [manually import the dashboard](https://grafana.com/docs/grafana/v9.0/dashboards/export-import/) json file that you want from the the [example dashboards folders](https://github.com/strimzi/strimzi-kafka-operator/tree/main/packaging/examples/metrics/grafana-dashboards) . 
2. Visit the dashboard, then save it as a raw dashboad JSON by following [this guide](https://grafana.com/docs/grafana/latest/administration/provisioning/#dashboards)  (i.e `Copy JSON to Clipboard` or `Save JSON to file`)
![image](https://user-images.githubusercontent.com/1930204/217247950-8c6a020f-d4b5-431f-a828-6ded31c9a7ab.png)

3. Use this JSON in your ConfigMap 

So it'd be great if you can report if that works without errors, so that maybe we can change the json files in the repo to the raw ones.

2023-02-07 15:56 UTC, nicl09 commented
I would love to try that but the kube-prometheus-stack doesn't seem to have the import option and I couldn't find a way to enable it.