Add CC deployment example with goals configured
strimzi/strimzi-kafka-operator pull request #8203
Opened 2023-03-07 19:05 UTC by kyguy

### Type of change

- Enhancement / new feature
- Documentation

### Description

- Adds new Cruise Control deployment example to demonstrate how to add custom goal lists
- Adds minor update to optimization goals documentation

### Checklist

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

2023-03-07 19:10 UTC, scholzj requested changes
You have to make the changes to `packaging/examples`

2023-03-07 19:16 UTC, scholzj approved these changes

2023-03-08 07:18 UTC, ppatierno approved these changes

2023-03-08 07:18 UTC, ppatierno approved these changes

2023-03-08 09:17 UTC, mimaison approved these changes

2023-03-09 09:08 UTC, PaulRMellor approved these changes
Looks good. I made a suggestion on the note.

2023-03-09 20:21 UTC, kyguy commented on documentation/modules/cruise-control/con-optimization-goals.adoc
> +NOTE: If you change the inherited main optimization goals or default goals, you must ensure that the hard goals, if configured in the `hard.goals` property in `Kafka.spec.cruiseControl.config`, are a
Thanks Paul, added your suggestion

2023-03-09 20:21 UTC, kyguy commented
This PR will be ready to merge once the tests pass successfully

2023-03-09 22:20 UTC, merged