Report script fix ppc64le
strimzi/strimzi-kafka-operator pull request #8824
Opened 2023-07-12 06:42 UTC by Vaibhav-Nazare

Fix for report_too.sh 
Expanding an array without an index only gives the element in the index 0.
```
./.azure/scripts/shellcheck.sh

In tools/report.sh line 34:
if [[ "$BASH_VERSINFO" -lt 4 ]]; then
^------------^ SC2128: Expanding an array without an index only gives the first element.
```

2023-07-12 06:45 UTC, scholzj commented
@Vaibhav-Nazare What shellcheck version are you using? Maybe you should sync it with the Strimzi CI which uses 0.7.2?

2023-07-12 07:19 UTC, fvaleri reviewed
Jakub is right, you are probably using shellcheck 0.7.1 or lower:

```sh
$ ./shellcheck-v0.7.1/shellcheck ~/Documents/strimzi-kafka-operator/tools/report.sh 

In /home/fvaleri/Documents/strimzi-kafka-operator/tools/report.sh line 34:
if [[ "$BASH_VERSINFO" -lt 4 ]]; then
       ^------------^ SC2128: Expanding an array without an index only gives the first element.

For more information:
  https://www.shellcheck.net/wiki/SC2128 -- Expanding an array without an ind...
```

2023-07-12 09:35 UTC, Vaibhav-Nazare commented
I did check this at our end it's higer
```
shellcheck -V
ShellCheck - shell script analysis tool
version: 0.9.0
license: GNU General Public License, version 3
website: https://www.shellcheck.net
```

2023-07-12 09:59 UTC, scholzj commented
Right. Then I think there are in general 2 options:
* You downgrade yours to 0.7.2 (instead of fixing the issue 0.9.0 reports). 
* Or you upgrade the one in our CI pipelines to 0.9.0 as well (plus fix the issue it reports). 

But running different versions and opening a PR each time it finds something different does not make sense. It might even happen that one day it has some conflicting issues. So bringing the versions in-sync one way or another will prevent this kind of issue from reappearing again and again.

I do not have a strong preference for which one to use - I guess updating the shellcheck version to 0.9.0 here might make more sense.

2023-07-12 10:11 UTC, Vaibhav-Nazare commented
Yes upgrading it too 0.9.0 makes more sense

2023-07-12 10:11 UTC, fvaleri commented
I also agree that we should upgrade shellcheck to 0.9.0 and fix the issue.

Note that the same check is also used in `docker-images/artifacts/build.sh` and `docker-images/kafka-based/build.sh`.

2023-07-12 11:29 UTC, scholzj approved these changes
Thanks for the changes!

2023-07-12 11:50 UTC, fvaleri requested changes

2023-07-12 11:50 UTC, fvaleri commented on tools/report.sh
> +if [[ "${BASH_VERSINFO[*]}" -lt 4 ]]; then
This is not correct, as we only care about the major version, so index 0. The same in the other places.

```sh
$ if [[ "${BASH_VERSINFO[*]}" -lt 4 ]]; then
  error "You need bash version >= 4 to run the script"
fi
bash: [[: 5 2 15 1 release x86_64-redhat-linux-gnu: syntax error in expression (error token is "2 15 1 release x86_64-redhat-linux-gnu")
```

2023-07-13 06:27 UTC, ppatierno approved these changes
LGTM.Thanks for the PR!

2023-07-13 07:29 UTC, fvaleri approved these changes
Thanks.

2023-07-13 09:09 UTC, scholzj commented
/azp run acceptance

2023-07-13 12:16 UTC, scholzj commented
Thanks for the PR

2023-07-13 12:16 UTC, merged