add new chart to strimzi kafka for ZK request latency and removed min…
strimzi/strimzi-kafka-operator pull request #9037
Opened 2023-08-25 15:46 UTC by ShazaAldawamneh

… and max request latency from zookeeper dashboard

### Type of change

- Bugfix
- Enhancement / new feature

### Description

add new chart to strimzi kafka for ZK request latency and removed min and max request latency from zookeeper dashboard

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ 1] Supply screenshots for visual changes, such as Grafana dashboards
![image](https://github.com/strimzi/strimzi-kafka-operator/assets/93832255/cc1a10d1-380d-4975-8c55-ff3447501d64)
![image](https://github.com/strimzi/strimzi-kafka-operator/assets/93832255/48358da0-d6ce-40d3-a11d-89423485f5d1)

2023-08-25 16:38 UTC, scholzj requested changes
You seem to have some conflict inthe PR. Also, you will need to copy the changes also into the Helm Chart (`make dashboard_install` IIRC).

2023-08-29 09:04 UTC, scholzj reviewed
@ShazaAldawamneh The dashboard changes look good to me. But can you get rid of the unrelated changes?

2023-08-29 09:35 UTC, ShazaAldawamneh commented
like what unrelated changes ? I think the other files have changed when I ran make crd_install     && make dashboard_install     && make helm_install @scholzj

2023-08-29 09:40 UTC, scholzj commented
> like what unrelated changes ? I think the other files have changed when I ran make crd_install && make dashboard_install && make helm_install @scholzj

You have for whatever reason some commits from me and Luke included in your PR. They are causing the changes to the other files. Your PR should have only 4 changed files -> the Grafana dashboards.

2023-08-29 09:43 UTC, ShazaAldawamneh commented
> > like what unrelated changes ? I think the other files have changed when I ran make crd_install && make dashboard_install && make helm_install @scholzj
> 
> You have for whatever reason some commits from me and Luke included in your PR. They are causing the changes to the other files. Your PR should have only 4 changed files -> the Grafana dashboards.

I see, will fix that

2023-08-29 12:26 UTC, scholzj approved these changes
LGTM. Thanks.

2023-08-31 09:36 UTC, scholzj commented
Note: this should resolve #1550

2023-09-03 14:13 UTC, ppatierno approved these changes
LGTM. Thanks!

2023-09-05 00:53 UTC, tombentley approved these changes
LGTM, thanks!

2023-09-05 08:12 UTC, merged

2024-04-08 07:50 UTC, pantaoran commented
I'm happy to see this improvement, but why wasn't this added also to the files under ´examples/metrics/grafana-dashboards/´ ?
Is that path not maintained anymore?

2024-04-08 07:59 UTC, scholzj commented
The `examples` directory (as well as `install` and `helm-charts` directories) contain the files from the last Strimzi release and are updated only as part of the release process. Any ongoing development and bugfixes to these files happens in the `packaging` directory. And when the next release happens, the changes are copied to the main directories.