docs(mm2): updates the section for running multiple instances
strimzi/strimzi-kafka-operator pull request #9057
Opened 2023-08-31 16:21 UTC by PaulRMellor

**Documentation**

Updates the section describing how to configure Kafka Connect when running multiple instances.
The section now also mentions MM2, which can be configured in the same way for the same reason.
The section moves into the configuring chapter, with  x-references from the sections describing how to deploy Kafka Connect and MM2.

Also includes a few naming updates for MM2.

### Description

_Please describe your pull request_

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

2023-08-31 16:23 UTC, PaulRMellor commented on documentation/modules/configuring/proc-config-kafka-connect-user-authorization.adoc
> -.Example configuration properties in the `KafkaConnect` resource
I removed this as we link to the multiple instances section instead. 
Should we also expand this KC authorization config section to include MM2?

2023-08-31 18:08 UTC, scholzj requested changes

2023-08-31 18:08 UTC, scholzj commented on documentation/modules/configuring/con-config-kafka-connect-mm2-multiple-instances.adoc
I'm not sure you can hide it that easily into one file:
* The configuration will be in different places. In Connect, it is `.spec.config` as you have it here. But for MM2, it will be in `config` section of the target cluster configuration. I.e. `.spec.clusters[].config` for the target cluster (bets to refer to it through the `connectCluster` field which is future-proof).
* MM2 also requires a bit more explanation of when it needs to be used. You need to use it when you have multiple MM2s which use the same `connectCluster`. So for example when you have one Kafka cluster used as a source cluster by two diffeent MM2s, you are fine. If you have two MM2s in active-active setup you are also fine as you have different `connectCluster` for each of them. Only when you have multiple MM2s with the same `connectCluster` you need this.

Given these references, I'm not sure whether two separate files one for each aren't better. But I leave that up to you. We just need to explain these differences.

2023-08-31 18:08 UTC, scholzj commented on documentation/modules/deploying/proc-deploy-kafka-mirror-maker.adoc
> +To do this, xref:con-kafka-connect-mm2-multiple-instances-{context}[configure each MirrorMaker 2 instance to replace the defaults].
As explain in the other comment. We should be more clear when does it need to be used with MM2.

2023-09-01 12:45 UTC, PaulRMellor commented on documentation/modules/configuring/con-config-kafka-connect-mm2-multiple-instances.adoc
Thanks. I'm trying to keep the content to a minimum where possible, but maybe too much here. I'll take another look for the next commit.

2023-09-01 13:30 UTC, scholzj commented on documentation/modules/configuring/con-config-kafka-connect-mm2-multiple-instances.adoc
To be clear, I don't have any major issue if you want to keep it in a single file if it makes things easier ... but the explanation would need to cover the differences.

2023-09-01 18:34 UTC, scholzj approved these changes
LGTM. Thanks.

2023-09-02 09:08 UTC, ppatierno approved these changes

2023-09-02 15:34 UTC, merged