[ST] Refactor - Rename systemtest.constants to testConstants
strimzi/strimzi-kafka-operator pull request #9296
Opened 2023-10-27 08:21 UTC by jankalinic

### Type of change

_Select the type of your PR_

- Bugfix
- Enhancement / new feature
- Refactoring
- Documentation

### Description

_Please describe your pull request_

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

2023-10-27 08:31 UTC, jankalinic commented
@strimzi-ci run tests --cluster-type=ocp --cluster-version=4.14 --install-type=bundle --testcase=UserST

2023-10-30 12:27 UTC, see-quick approved these changes
Assuming the test is going to pass.  LGTM

2023-11-02 09:49 UTC, Frawless approved these changes

2023-11-02 10:28 UTC, jankalinic commented on systemtest/src/main/java/io/strimzi/systemtest/TestConstants.java
> +    String PATH_TO_KAFKA_MIRROR_MAKER_2_METRICS_CONFIG = TestConstants.PATH_TO_PACKAGING_EXAMPLES + "/metrics/kafka-mirror-maker-2-metrics.yaml";
Thanks! Thats a good catch! sorry for that.

2023-11-02 10:41 UTC, jankalinic commented on systemtest/src/test/java/io/strimzi/systemtest/AbstractST.java
>      public static final String TOPIC_NAME = KafkaTopicUtils.generateRandomNameOfTopic();
Can do that in another PR! Thanks

2023-11-02 10:55 UTC, jankalinic commented on systemtest/src/main/java/io/strimzi/systemtest/utils/kafkaUtils/KafkaConnectorUtils.java
> +                          () -> (KafkaConnectorResource.kafkaConnectorClient().inNamespace(namespaceName)
Will change that, thanks

2023-11-09 10:11 UTC, jankalinic commented
Tests on azp buildId=155378 finished with one error -> testKafkaDoesNotRollsWhenTopicIsUnderReplicated

2023-11-09 10:17 UTC, im-konge commented
/azp run regression

2023-11-09 23:51 UTC, jankalinic commented
I think this PR is ready to be merged as AZP showed only unrelated test ->testKafkaDoesNotRollsWhenTopicIsUnderReplicated failing.

2023-11-10 03:02 UTC, scholzj commented
@im-konge Do you have any more comments on this? Or should we proceed and merge this? You seem to have commented but did not approve.

2023-11-10 08:22 UTC, im-konge requested changes
You are changing indentations and test descriptions even if it's not the main target of the PR. I left few comments, please check the whole classes and fix the things you broke in the last commit. Thanks

2023-11-10 08:22 UTC, im-konge commented on systemtest/src/test/java/io/strimzi/systemtest/bridge/HttpBridgeKafkaExternalListenersST.java
> +            .withTrustedCertificates(certSecret)
You are changing indentation in the whole class, why?

2023-11-10 08:22 UTC, im-konge commented on systemtest/src/test/java/io/strimzi/systemtest/log/LogSettingST.java
> +            .endJvmOptions()
Here as well

2023-11-10 08:22 UTC, im-konge commented on systemtest/src/test/java/io/strimzi/systemtest/log/LoggingChangeST.java
> +            .withNamespace(namespaceName)
Here as well

2023-11-10 08:22 UTC, im-konge commented on systemtest/src/test/java/io/strimzi/systemtest/metrics/MetricsST.java
> + * - All resources deleted.
Why are you changing the lines etc.?

2023-11-10 08:22 UTC, im-konge commented on systemtest/src/test/java/io/strimzi/systemtest/metrics/MetricsST.java
> +            .build();
Again indent

2023-11-10 08:22 UTC, im-konge commented on systemtest/src/test/java/io/strimzi/systemtest/operators/topic/TopicST.java
> +            .withNamespace(Environment.TEST_SUITE_NAMESPACE)
Here as well

2023-11-10 08:22 UTC, im-konge commented on systemtest/src/test/java/io/strimzi/systemtest/rollingupdate/RollingUpdateST.java
> +     * - scale-down
Why is it changed? It's completely un-related to the PR description

2023-11-10 08:22 UTC, im-konge commented on systemtest/src/test/java/io/strimzi/systemtest/rollingupdate/RollingUpdateST.java
> +                .endMetadata()
Indent

2023-11-20 18:46 UTC, im-konge approved these changes
LGTM, thanks for the changes.

2023-11-22 13:19 UTC, im-konge commented
/azp run regression

2023-11-22 20:29 UTC, merged