docs(topic operator): describes the tuning for topic operator batching mechanism
strimzi/strimzi-kafka-operator pull request #9314
Opened 2023-11-01 17:07 UTC by PaulRMellor

**Documentation**

New section to describe how to  tune the batching mechanism used by the UTO using operator config properties.

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

2023-11-02 11:14 UTC, fvaleri requested changes
Thanks. Looks good, just some suggestions.

2023-11-02 11:14 UTC, fvaleri commented on documentation/modules/operators/con-tuning-topic-request-batches.adoc
> +* `STRIMZI_MAX_QUEUE_SIZE` to set the maximum size of the request batching queue.
```suggestion
* `STRIMZI_MAX_QUEUE_SIZE` to set the maximum size of the topic event queue. 
```

2023-11-02 11:14 UTC, fvaleri commented on documentation/modules/operators/con-tuning-topic-request-batches.adoc
> +* `STRIMZI_MAX_BATCH_SIZE` to set the maximum number of requests allowed in a single batch.
```suggestion
* `STRIMZI_MAX_BATCH_SIZE` to set the maximum number of topic events allowed in a single batch. 
```

2023-11-02 11:14 UTC, fvaleri commented on documentation/modules/operators/con-tuning-topic-request-batches.adoc
> +The default value is 100 requests for operations to create, update, or delete topics.
```suggestion
The default value is 100.
```

2023-11-02 11:14 UTC, fvaleri commented on documentation/modules/operators/con-tuning-topic-request-batches.adoc
> +* `MAX_BATCH_LINGER_MS` to specify the time to wait for a request batch to accumulate `STRIMZI_MAX_BATCH_SIZE` items before processing.
```suggestion
* `MAX_BATCH_LINGER_MS` to specify the max time to wait for a batch to accumulate items before processing. 
```

2023-11-04 07:32 UTC, ppatierno approved these changes
LGTM.

2023-11-08 15:25 UTC, fvaleri approved these changes

2023-11-08 15:35 UTC, merged